package com.financecrm.webportal.enums;

public enum BankName {
    AK_BANK,
    ALTERNATIF_BANK,
    ANADOLU_BANK,
    BURGAN_BANK,
    CITI_BANK,
    DENIZ_BANK,
    DEUTSCHE_BANK,
    FIBA_BANK,
    HABIB_BANK,
    HSBC_BANK,
    ICBC_BANK,
    ING_BANK,
    JPMORGAN ,
    ODEA_BANK,     
    QNBFINANS_BANK,
    RABO_BANK,
    SEKER_BANK,
    ZIRAAT_BANKASI,
    TURKLAND_BANK,
    TURKEKONOMI_BANKASI,
    GARANTI_BANKASI,
    HALK_BANKASI,
    IS_BANKASI,
    TURKIYEVAKIFLAR_BANKASI,
    YAPIKREDI_BANKASI,
    TEST
    
}
